project_id = "ssnmuiskarajydbtwgto"

[functions.send-invitation-email]
verify_jwt = true

[functions.send-payment-reminder]
verify_jwt = true

[functions.send-notifications]
verify_jwt = true



[functions.send-comunicado]
verify_jwt = true

[functions.create-infinitepay-link]
verify_jwt = false

[functions.infinitepay-webhook]
verify_jwt = false

[functions.redeem-invitation]
enabled = true
verify_jwt = true
import_map = "./functions/redeem-invitation/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/redeem-invitation/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/redeem-invitation/*.html" ]
