project_id = "wanvrxtpqvxvczuzqhui"

[functions.send-invitation-email]
verify_jwt = true

[functions.send-payment-reminder]
verify_jwt = true

[functions.send-notifications]
verify_jwt = true



[functions.send-comunicado]
verify_jwt = true

[functions.create-infinitepay-link]
verify_jwt = false

[functions.infinitepay-webhook]
verify_jwt = false
